model_name: "t5-small"
pretrained: False
#tokenizer_name: "t5-small-rest_e2e-lowercase"
slot_name_conversion: "special_tokens"
num_epochs: 30
batch_size: 56
max_seq_length: 128
num_warmup_steps: 0
lr: 2.0e-4
max_grad_norm: 1.0
eval_times_per_epoch: 1
#eval_every_n_epochs: 5
fp16: True
