model_name: "t5-base"
pretrained: True
lowercase: False
slot_name_conversion: "verbalize"
balance_training_data: True
num_epochs: 20
batch_size: 1
eval_batch_size: 64
max_seq_length: 128
num_warmup_steps: 20
lr: 1.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
