model_name: "facebook/bart-base"
pretrained: True
convert_slot_names: True
num_epochs: 5
batch_size: 20
max_seq_length: 512
num_warmup_steps: 500
lr: 5.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 4
fp16: True
