model_name: "facebook/bart-base"
pretrained: True
convert_slot_names: True
num_epochs: 20
batch_size: 20
max_seq_length: 128
num_warmup_steps: 50
lr: 1.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
