model_name: "facebook/bart-base"
pretrained: True
lowercase: False
convert_slot_names: False
num_epochs: 25
batch_size: 32
eval_batch_size: 128
max_seq_length: 160
num_warmup_steps: 500
lr: 1.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
