model_name: "facebook/bart-base"
pretrained: True
convert_slot_names: True
num_epochs: 15
batch_size: 32
max_seq_length: 128
num_warmup_steps: 500
lr: 1.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
