pretrained_model: "facebook/bart-base"
convert_slot_names: True
num_epochs: 10
batch_size: 12
max_seq_length: 512
num_warmup_steps: 400
lr: 1.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 2
fp16: True
