model_name: "seq2seq/export/rest_e2e/finetuned/bart-base_lr_1e-5_bs_32_wus_500/epoch_11_step_657"
pretrained: True
convert_slot_names: True
num_epochs: 10
batch_size: 20
max_seq_length: 128
num_warmup_steps: 100
lr: 1.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
