model_name: "gpt2"
pretrained: False
#tokenizer_name: "gpt2-video_game"
convert_slot_names: True
num_epochs: 35
batch_size: 16
max_seq_length: 256
num_warmup_steps: 0
lr: 2.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 1
#eval_every_n_epochs: 2
fp16: True
