model_name: "seq2seq/export/rest_e2e/finetuned/t5-small_lr_1e-4_bs_64_wus_500/epoch_10_step_658"
pretrained: True
convert_slot_names: True
num_epochs: 20
batch_size: 48
max_seq_length: 128
num_warmup_steps: 100
lr: 2.0e-4
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
