model_name: "t5-small"
pretrained: True
lowercase: False
slot_name_conversion: "verbalize"
num_epochs: 20
batch_size: 8
eval_batch_size: 256
max_seq_length: 128
num_warmup_steps: 60
lr: 2.0e-4
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
