model_name: "t5-small"
pretrained: True
convert_slot_names: True
num_epochs: 15
batch_size: 32
max_seq_length: 160
num_warmup_steps: 500
lr: 2.0e-4
max_grad_norm: 1.0
#eval_times_per_epoch: 1
eval_every_n_epochs: 1
fp16: True
