model_name: "t5-small"
pretrained: True
lowercase: False
convert_slot_names: False
num_epochs: 20
batch_size: 64
eval_batch_size: 512
max_seq_length: 128
num_warmup_steps: 100
lr: 2.0e-4
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
