model_name: "facebook/bart-base"
pretrained: False
tokenizer_name: "bart-base-video_game"
lowercase: False
slot_name_conversion: "verbalize"
num_epochs: 40
batch_size: 32
eval_batch_size: 64
max_seq_length: 128
num_warmup_steps: 0
lr: 2.0e-5
max_grad_norm: 1.0
#eval_times_per_epoch: 1
eval_every_n_epochs: 1
fp16: True
