model_name: "gpt2"
pretrained: False
tokenizer_name: "gpt2-video_game"
lowercase: False
slot_name_conversion: "verbalize"
num_epochs: 25
batch_size: 16
eval_batch_size: 64
max_seq_length: 160
num_warmup_steps: 0
lr: 3.0e-5
max_grad_norm: 1.0
#eval_times_per_epoch: 1
eval_every_n_epochs: 1
fp16: True
use_token_type_ids: True
