model_name: "t5-base"
pretrained: True
lowercase: False
slot_name_conversion: "verbalize"
num_epochs: 20
batch_size: 16
eval_batch_size: 64
max_seq_length: 128
num_warmup_steps: 100
lr: 3.0e-5
max_grad_norm: 1.0
eval_times_per_epoch: 1
fp16: True
